// Generated by gencpp from file learning_topic/tele_cam_zoom.msg
// DO NOT EDIT!


#ifndef LEARNING_TOPIC_MESSAGE_TELE_CAM_ZOOM_H
#define LEARNING_TOPIC_MESSAGE_TELE_CAM_ZOOM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace learning_topic
{
template <class ContainerAllocator>
struct tele_cam_zoom_
{
  typedef tele_cam_zoom_<ContainerAllocator> Type;

  tele_cam_zoom_()
    : zoom_pos(0)  {
    }
  tele_cam_zoom_(const ContainerAllocator& _alloc)
    : zoom_pos(0)  {
  (void)_alloc;
    }



   typedef uint32_t _zoom_pos_type;
  _zoom_pos_type zoom_pos;





  typedef boost::shared_ptr< ::learning_topic::tele_cam_zoom_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::learning_topic::tele_cam_zoom_<ContainerAllocator> const> ConstPtr;

}; // struct tele_cam_zoom_

typedef ::learning_topic::tele_cam_zoom_<std::allocator<void> > tele_cam_zoom;

typedef boost::shared_ptr< ::learning_topic::tele_cam_zoom > tele_cam_zoomPtr;
typedef boost::shared_ptr< ::learning_topic::tele_cam_zoom const> tele_cam_zoomConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::learning_topic::tele_cam_zoom_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::learning_topic::tele_cam_zoom_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::learning_topic::tele_cam_zoom_<ContainerAllocator1> & lhs, const ::learning_topic::tele_cam_zoom_<ContainerAllocator2> & rhs)
{
  return lhs.zoom_pos == rhs.zoom_pos;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::learning_topic::tele_cam_zoom_<ContainerAllocator1> & lhs, const ::learning_topic::tele_cam_zoom_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace learning_topic

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::learning_topic::tele_cam_zoom_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::learning_topic::tele_cam_zoom_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learning_topic::tele_cam_zoom_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learning_topic::tele_cam_zoom_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learning_topic::tele_cam_zoom_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learning_topic::tele_cam_zoom_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::learning_topic::tele_cam_zoom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8a87238ba8464f0ef4168b3664211fc9";
  }

  static const char* value(const ::learning_topic::tele_cam_zoom_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8a87238ba8464f0eULL;
  static const uint64_t static_value2 = 0xf4168b3664211fc9ULL;
};

template<class ContainerAllocator>
struct DataType< ::learning_topic::tele_cam_zoom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "learning_topic/tele_cam_zoom";
  }

  static const char* value(const ::learning_topic::tele_cam_zoom_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::learning_topic::tele_cam_zoom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 zoom_pos\n"
;
  }

  static const char* value(const ::learning_topic::tele_cam_zoom_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::learning_topic::tele_cam_zoom_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.zoom_pos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct tele_cam_zoom_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::learning_topic::tele_cam_zoom_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::learning_topic::tele_cam_zoom_<ContainerAllocator>& v)
  {
    s << indent << "zoom_pos: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.zoom_pos);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEARNING_TOPIC_MESSAGE_TELE_CAM_ZOOM_H
