// Generated by gencpp from file learning_topic/video_cam.msg
// DO NOT EDIT!


#ifndef LEARNING_TOPIC_MESSAGE_VIDEO_CAM_H
#define LEARNING_TOPIC_MESSAGE_VIDEO_CAM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace learning_topic
{
template <class ContainerAllocator>
struct video_cam_
{
  typedef video_cam_<ContainerAllocator> Type;

  video_cam_()
    : zoom_pos(0)
    , tempature(0)
    , stabilize(false)
    , focus_mode(false)
    , defog(0)  {
    }
  video_cam_(const ContainerAllocator& _alloc)
    : zoom_pos(0)
    , tempature(0)
    , stabilize(false)
    , focus_mode(false)
    , defog(0)  {
  (void)_alloc;
    }



   typedef uint32_t _zoom_pos_type;
  _zoom_pos_type zoom_pos;

   typedef int8_t _tempature_type;
  _tempature_type tempature;

   typedef uint8_t _stabilize_type;
  _stabilize_type stabilize;

   typedef uint8_t _focus_mode_type;
  _focus_mode_type focus_mode;

   typedef uint8_t _defog_type;
  _defog_type defog;





  typedef boost::shared_ptr< ::learning_topic::video_cam_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::learning_topic::video_cam_<ContainerAllocator> const> ConstPtr;

}; // struct video_cam_

typedef ::learning_topic::video_cam_<std::allocator<void> > video_cam;

typedef boost::shared_ptr< ::learning_topic::video_cam > video_camPtr;
typedef boost::shared_ptr< ::learning_topic::video_cam const> video_camConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::learning_topic::video_cam_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::learning_topic::video_cam_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::learning_topic::video_cam_<ContainerAllocator1> & lhs, const ::learning_topic::video_cam_<ContainerAllocator2> & rhs)
{
  return lhs.zoom_pos == rhs.zoom_pos &&
    lhs.tempature == rhs.tempature &&
    lhs.stabilize == rhs.stabilize &&
    lhs.focus_mode == rhs.focus_mode &&
    lhs.defog == rhs.defog;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::learning_topic::video_cam_<ContainerAllocator1> & lhs, const ::learning_topic::video_cam_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace learning_topic

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::learning_topic::video_cam_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::learning_topic::video_cam_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learning_topic::video_cam_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learning_topic::video_cam_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learning_topic::video_cam_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learning_topic::video_cam_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::learning_topic::video_cam_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6b7dd9479180d3c3cd4356c8658745b5";
  }

  static const char* value(const ::learning_topic::video_cam_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6b7dd9479180d3c3ULL;
  static const uint64_t static_value2 = 0xcd4356c8658745b5ULL;
};

template<class ContainerAllocator>
struct DataType< ::learning_topic::video_cam_<ContainerAllocator> >
{
  static const char* value()
  {
    return "learning_topic/video_cam";
  }

  static const char* value(const ::learning_topic::video_cam_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::learning_topic::video_cam_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 zoom_pos\n"
"int8 tempature\n"
"bool stabilize      # 1 for enabled\n"
"bool focus_mode     # 0 for manual, 1 for auto\n"
"uint8 defog         # level 0: low, 1: mid, 2:high\n"
;
  }

  static const char* value(const ::learning_topic::video_cam_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::learning_topic::video_cam_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.zoom_pos);
      stream.next(m.tempature);
      stream.next(m.stabilize);
      stream.next(m.focus_mode);
      stream.next(m.defog);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct video_cam_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::learning_topic::video_cam_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::learning_topic::video_cam_<ContainerAllocator>& v)
  {
    s << indent << "zoom_pos: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.zoom_pos);
    s << indent << "tempature: ";
    Printer<int8_t>::stream(s, indent + "  ", v.tempature);
    s << indent << "stabilize: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.stabilize);
    s << indent << "focus_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.focus_mode);
    s << indent << "defog: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.defog);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEARNING_TOPIC_MESSAGE_VIDEO_CAM_H
